import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the `mcbe` docs instance (plugin id: `mcbe`, path: `docs-mcbe`).
 *
 * The exported key MUST stay unique across all docs instances: it becomes the
 * `sidebarId` referenced by the navbar item and by `docSidebar` links.
 */
const sidebars: SidebarsConfig = {
  mcbeSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
